---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: secret-mysql
  namespace: database
spec:
  encryptedData:
    password: AgAWLhRETUAco+DnlywzHk/sMm0wDIf766qluEGwW5mJMXotcJSouaMVufGnYWjzGwHxpd+tV9mPz1WpjjsSfF0QR0Km3cNg1Hn/2JZDd0lhITl0dQsSkZkqGVCERlslnbMF//hs8uvJn6wh7gDqP39uzw59Hb1lqEVn44KGM2LcXbGgerXpVUfs/zbDvOdRdGC7aq1APrm57/tpr+JQk1eublowCHu6jN1zZzchH8hX1oou8awsF/7t+4O4Jgu90cGvJjjJqyncduojvuqPus3K5EPRBC1KJGpVVbQQcskMZ/d24jLSuWBXXYGrjRTZPCUWmn4CPOiFZwtyTO2TL5TjtzykKpdrZSDkAOOT5zfvY4CPk0TGywRf4lktPLsMVFn8O63tniaF2jcD7aOKokidkty7Sc/4JTLpKq2S1rAJK+mzc8YaXPl6E7xwd0xwWRqZqqJBh2+Owax6FCdIV8coPRnrw0aMzmdMTFudChLF0pl8h/WQPEYCmfxXvOXnKzjBSM6tKoG13WHhHlwOReG8WEZHY0KIN4jHjbJRuNHjkhrDRiF2f7ylH7ozYW/sSG4//WA/b8RszCqQX0dYA67ibt5lMdcRrwtimtnV360r09k6OO7W2ZESct2aXVLhcxUafX9khG6rynMFhd9Jf89xym+WDcQMsYLbWi/7bUCTmDKXpNzWlmnLAHvNzw+mwsu+ysqgY4GDzv3/UWgdqPEjpF5QOtIdOSXS
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: secret-mysql
      namespace: database
